"""
Core application module.
"""

from .config import (
    APP_TITLE, DEFAULT_MAP_CENTER, DEFAULT_MAP_ZOOM,
    DEFAULT_OCCUPANTS, DEFAULT_OCCUPANT_WEIGHT,
    DEFAULT_CG_MIN, DEFAULT_CG_MAX, DEFAULT_FUEL_LOAD,
    DEFAULT_OAT_C, DEFAULT_ALTIMETER_INHG,
    DEFAULT_WIND_DIR, DEFAULT_WIND_SPEED,
    DEFAULT_TIMESTEP_SEC, DEFAULT_MAX_BANK_DEG
)

from .app_factory import app, server, create_app

__all__ = [
    # Config
    'APP_TITLE', 'DEFAULT_MAP_CENTER', 'DEFAULT_MAP_ZOOM',
    'DEFAULT_OCCUPANTS', 'DEFAULT_OCCUPANT_WEIGHT',
    'DEFAULT_CG_MIN', 'DEFAULT_CG_MAX', 'DEFAULT_FUEL_LOAD',
    'DEFAULT_OAT_C', 'DEFAULT_ALTIMETER_INHG',
    'DEFAULT_WIND_DIR', 'DEFAULT_WIND_SPEED',
    'DEFAULT_TIMESTEP_SEC', 'DEFAULT_MAX_BANK_DEG',
    # App
    'app', 'server', 'create_app',
]
